#!/usr/bin/env python3
"""make_manifest.py -- build MANIFEST.md for the publication package.

Reads the package tree, records size and sha256 for every file, and writes a
manifest grouped by folder. Read-only over the package; writes only MANIFEST.md.
"""
import hashlib
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
SKIP_DIRS = {"__pycache__", ".git"}


def sha256(path, bufsize=1 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        while True:
            b = fh.read(bufsize)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def walk(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            if name == "MANIFEST.md":
                continue
            yield os.path.join(dirpath, name)


def main():
    rows = []
    total = 0
    for path in walk(ROOT):
        rel = os.path.relpath(path, ROOT)
        size = os.path.getsize(path)
        total += size
        rows.append((rel, size, sha256(path)))

    by_dir = {}
    for rel, size, digest in rows:
        d = os.path.dirname(rel) or "."
        by_dir.setdefault(d, []).append((os.path.basename(rel), size, digest))

    out = []
    out.append("# MANIFEST — publication package, EMCA / agent_arch v1–v20\n")
    out.append(
        "Every file in this package with its byte size and SHA-256. Generated by "
        "`make_manifest.py` (read-only over the tree). "
        f"Files: **{len(rows)}**, total bytes: **{total}** "
        f"({total / (1024 * 1024):.1f} MiB).\n"
    )
    out.append(
        "The frozen artefacts named in the reports hash to the values the reports "
        "record; the section documents quote those values. The raw matrices are "
        "included in full so a reader can re-derive every number.\n"
    )
    for d in sorted(by_dir):
        out.append(f"## `{d}/`\n")
        out.append("| file | bytes | sha256 |")
        out.append("|---|---:|---|")
        for name, size, digest in sorted(by_dir[d]):
            out.append(f"| `{name}` | {size} | `{digest}` |")
        out.append("")

    with open(os.path.join(ROOT, "MANIFEST.md"), "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote MANIFEST.md: {len(rows)} files, {total} bytes")


if __name__ == "__main__":
    main()